# toml-docs-start main
[main]
    separator = "-"
    description = "A versatile OAuth2 authorization server and Traefik middleware for Kubernetes and Docker."
    enableDarkMode = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    endorse = false
    footer = false
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "libsass"
# toml-docs-end main

# toml-docs-start modules
[modules]
    core = ["bootstrap", "flexsearch", "fontawesome"]
    optional = ["leaflet", "katex", "lottie"]
    excludeSCSS = ["bootstrap"]
    disableTemplate = ["katex"]
    [modules.katex]
        state = "defer"
    [modules.fontawesome]
        inline = true
        debug = true
        skipMissing = false
# toml-docs-end modules

# toml-docs-start debugging
[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = false
# toml-docs-end debugging

# toml-docs-start docs
[docs]
    github = "https://github.com/uitsmijter"
    release = "https://charts.uitsmijter.io"
    checkVersion = false
# toml-docs-end docs

# toml-docs-start home
[home]
    sections = ["articles"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "none"
        width = 6
        align = "start"
# toml-docs-end home

# toml-docs-start navigation
[navigation]
    anchor = true
    logo = "/img/logo_icon.svg"
    color = "body"
    fixed = true
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
    colorSwitch = false
# toml-docs-end navigation

# toml-docs-start messages
[messages]
    placement = "bottom-right"
# toml-docs-end messages

# toml-docs-start sharing
[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

# Twitter/X removed
# [[sharing.providers]]
#     name = "Twitter"
#     url = "https://twitter.com/home?status={url}"
#     icon = "fab x-twitter"
#     weight = 20

[[sharing.providers]]
    name = "Mastodon"
    url = "https://mastodonshare.com/?url={url}"
    icon = "fab mastodon"
    weight = 21

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

# toml-docs-end sharing

# toml-docs-start sections
[sections]
    [sections.articles]
        title = "Articles"
        sort = "date"
        reverse = true
        nested = true
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom card-body-margin"
        homepage = 3
        separator = true
# toml-docs-end sections

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#ff9e00" # "#d43900"
    secondary = "#ff1e00"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#dbdbdb"
    dark = "#4a4a4a"
# toml-docs-end theme-colors
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
# toml-docs-start font
    themeFont = "Source Sans Pro Regular"
    headlineFont = "Playfair Display"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    fontSizeBase = "1rem" # assumes the browser default, typically '16px'
# toml-docs-end font
# toml-docs-start build
    purge = false
# toml-docs-end build

[schema]
    type = "Organization"
    name = "Uitsmijter"
    locale = "en-US"
    # twitter = ""
    # linkedIn = ""
    github = "https://github.com/uitsmijter"
    section = "blog"
    [author]
        name = "Uitsmijter"
        # twitter = "https://twitter.com/markdumay"
        # linkedin = "https://www.linkedin.com/in/markdumay/"
        github = "https://github.com/uitsmijter"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[comments]
	discourseUrl = "https://discourse.uitsmijter.io/"
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = ""

[links]
    hinode = "https://uitsmijter.io"
