[[main]]
  name = "Articles"
  #pre = "fab home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Tags"
  #pre = "fab tags"
  pageRef = "/tags"
  weight = 20
  
[[main]]
  name = "RSS"
  #pre = "fa square-rss"
  pageRef = "https://articles.uitsmijter.io/index.xml"
  weight = 30  

[[social]]
  name = "Mastodon"
  pre = "fab mastodon"
  url = "https://social.uitsmijter.io/public/local"
  weight = 10

[[social]]
  name = "Discourse"
  pre = "fab discourse"
  url = "https://discourse.uitsmijter.io/"
  weight = 20
  
[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/uitsmijter"
  weight = 30


